### ISSUE TITLE
Unexpected value JwPaginationComponent ng build --prod

### ISSUE THREAD

**Issue by ridwan85** [cornflourblue/jw-angular-pagination#1]
Hi, when trying to build with ng build --prod . This library throw an error

> Unexpected value 'JwPaginationComponent in /Users/firmcode1/Documents/projects/fiction-project/production/node_modules/jw-angular-pagination/lib/jw-pagination.component.d.ts' declared by the module 'AppModule in /Users/firmcode1/Documents/projects/fiction-project/production//src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

**Comment by cornflourblue** [comment]
Hi @ridwan85, this should be fixed now with version 1.0.5

I just needed to generate and publish the .metadata.json file to npm
