### ISSUE TITLE
BS4 Pagination Styles

### ISSUE THREAD

**Issue by thomaspalmer** [cornflourblue/jw-angular-pagination#3]
Hi There

Are you planning to add the BS4 pagination styles? For now I have added them myself (quite hacky) however will loose them when deploying. I have tested and you can add the classes without effecting BS3 support.

Look forward to hearing from you.

Tom

**Comment by HunteRoi** [comment]
Hey! It seems like the component does already supported BootStrap 4 pagination styles.

**Comment by thomaspalmer** [comment]
@HunteRoi Correct... but that was added after the 23rd July 2018. I've fallen out of love with Angular anyway :/
